"""Synthetic-only contract, safety, alignment and render tests (stdlib unittest)."""
import copy
import json
import os
from pathlib import Path
import subprocess
import sys
import unittest
import av
import numpy as np
from PIL import Image
from synthetic_demo import ROOT, fixtures, call_worker

sys.path.insert(0, str(ROOT / "python"))
from paper_director.media import mix_audio, decode_audio, probe
from paper_director.renderer import Painter, validate_timeline
from paper_director.safety import assets_mapping, MediaError


class WorkerTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Every test-generated byte stays in an explicit output directory within the owned scope.
        cls.output = ROOT / "tests" / "python" / ".artifacts" / "unit"
        cls.output.mkdir(parents=True, exist_ok=True)
        cls.data = fixtures(cls.output)
        cls.counter = 0

    def request(self, request):
        type(self).counter += 1
        return call_worker(request, self.output / f"job-{self.counter}")

    def test_probe_sniffs_bytes_not_extension(self):
        fake = self.output / "actually-an-image.exe"
        fake.write_bytes(Path(self.data["assets"]["image0"]["path"]).read_bytes())
        process, value = self.request({"action": "probe", "inputPath": str(fake)})
        self.assertEqual(process.returncode, 0)
        self.assertEqual(value["result"]["format"], "png")
        self.assertEqual(value["result"]["width"], 640)
        stages = [json.loads(line) for line in process.stdout.splitlines()]
        self.assertEqual(stages[-1]["progress"], 1)
        self.assertTrue(all(0 <= item["progress"] <= 1 for item in stages))

    def test_probe_rejects_svg_playlist_corruption_and_url(self):
        for name, payload in (("evil.png", b'<svg onload="eval(1)"/>'), ("playlist.wav", b"#EXTM3U\nhttps://example.invalid/audio"), ("broken.png", b"\x89PNG\r\n\x1a\nBAD")):
            path = self.output / name
            path.write_bytes(payload)
            _, result = self.request({"action": "probe", "inputPath": str(path)})
            self.assertFalse(result["ok"])
        _, value = self.request({"action": "probe", "inputPath": "https://example.invalid/private.wav"})
        self.assertEqual(value["error"]["code"], "UNSAFE_PATH")

    def test_bad_schema_cannot_run_commands(self):
        marker = self.output / "must-not-exist"
        _, result = self.request({"action": "probe", "inputPath": self.data["assets"]["recording"]["path"], "command": f"touch {marker}"})
        self.assertEqual(result["error"]["code"], "INVALID_REQUEST")
        self.assertFalse(marker.exists())
        self.assertNotIn(str(self.output), result["error"]["message"])

    def test_provided_segments_preserves_author_and_unmatched(self):
        scenes = [{"id": "scene", "dialogue": [{"id": "first", "characterId": "paper", "text": "hello there"}, {"id": "missing", "characterId": "clock", "text": "never spoken"}]}]
        _, value = self.request({"action": "align", "inputPath": self.data["assets"]["recording"]["path"], "engine": "segments",
                                 "scenes": scenes, "characters": self.data["characters"],
                                 "segments": [{"start": 0, "end": .5, "text": "helo there", "dialogueId": "first"}, {"start": 1, "end": 1.4, "text": "extra unexpected words"}]})
        self.assertTrue(value["ok"], value)
        alignment = value["result"]
        first, missing = alignment["utterances"]
        self.assertEqual(first["authorText"], "hello there")
        self.assertEqual(first["recognizedText"], "helo there")
        self.assertEqual(first["characterId"], "paper")
        self.assertEqual(missing["matchStatus"], "unmatched")
        self.assertIsNone(missing["start"])
        self.assertIsNone(missing["end"])
        self.assertEqual(alignment["unmatchedSpeech"][0]["text"], "extra unexpected words")
        self.assertEqual(alignment["method"], "provided_segments")

    def test_segments_need_valid_times_and_no_fake_fallback(self):
        request = {"action": "align", "inputPath": self.data["assets"]["recording"]["path"], "engine": "segments", "scenes": self.data["scenes"], "characters": self.data["characters"]}
        for segments in (None, [{"start": -1, "end": 1, "text": "no"}], [{"start": 0, "end": 9, "text": "no"}], [{"start": 1, "end": 1, "text": "no"}]):
            _, result = self.request({**request, "segments": segments})
            self.assertFalse(result["ok"])
        _, result = self.request({**request, "segments": []})
        self.assertTrue(result["ok"])
        self.assertTrue(all(item["recognizedText"] == "" and item["start"] is None for item in result["result"]["utterances"]))

    def test_real_asr_requires_existing_complete_model(self):
        for engine in ("whisper", "vosk"):
            _, result = self.request({"action": "align", "inputPath": self.data["assets"]["recording"]["path"], "scenes": [], "characters": [], "engine": engine, "modelPath": str(self.output / "missing-model")})
            self.assertEqual(result["error"]["code"], "MODEL_NOT_READY")

    def test_audio_segments_and_overlays_sample_exact(self):
        timeline = copy.deepcopy(self.data["timeline"])
        mapped = assets_mapping(self.data["assets"])
        audio, warnings = mix_audio(timeline, mapped, "recording")
        source = decode_audio(mapped["recording"]["path"])
        overlay = decode_audio(mapped["chime"]["path"])
        self.assertTrue(np.all(audio[:, :24000] == 0))
        np.testing.assert_array_equal(audio[:, 24000:96000], source[:, :72000])
        np.testing.assert_array_equal(audio[:, 120000:192000], source[:, 72000:144000])
        np.testing.assert_allclose(audio[:, 96000:115200], overlay * (10 ** (-3 / 20)), atol=1e-7)
        self.assertTrue(np.all(audio[:, 240000:] == 0))
        self.assertFalse(warnings)

    def test_frame_uses_identical_painter(self):
        _, value = self.request({"action": "frame", "timeline": self.data["timeline"], "assets": self.data["assets"], "time": 1.5})
        self.assertTrue(value["ok"], value)
        folder = self.output / f"job-{self.counter}"
        actual = np.asarray(Image.open(folder / "frame.png"))
        expected = np.asarray(Painter(self.data["timeline"], assets_mapping(self.data["assets"])).draw(1.5))
        np.testing.assert_array_equal(actual, expected)

    def test_h264_aac_bt709_render_and_frame_equivalence(self):
        _, value = self.request({"action": "render", "timeline": self.data["timeline"], "assets": self.data["assets"], "recordingAssetId": "recording"})
        self.assertTrue(value["ok"], value)
        movie_path = self.output / f"job-{self.counter}" / "movie.mp4"
        painter = Painter(self.data["timeline"], assets_mapping(self.data["assets"]))
        with av.open(str(movie_path)) as movie:
            video, audio = movie.streams.video[0], movie.streams.audio[0]
            self.assertEqual(video.codec_context.name, "h264")
            self.assertEqual(audio.codec_context.name, "aac")
            self.assertEqual(video.codec_context.color_range, 1)
            self.assertEqual(video.codec_context.colorspace, 1)
            self.assertEqual(video.codec_context.color_primaries, 1)
            self.assertEqual(video.codec_context.color_trc, 1)
            self.assertAlmostEqual(movie.duration / av.time_base, 5.5, delta=.1)
            frames = list(movie.decode(video=0))
            self.assertEqual(len(frames), 66)
            expected = np.asarray(painter.draw(18 / 12), dtype=np.float32)
            actual = frames[18].to_ndarray(format="rgb24").astype(np.float32)
            self.assertLess(np.abs(actual - expected).mean(), 8)
        with av.open(str(movie_path)) as movie:
            self.assertGreater(sum(frame.samples for frame in movie.decode(audio=0)), 260000)

    def test_timeline_rejects_unmapped_null_huge_and_untrusted_paths(self):
        for change in ({"width": 100000}, {"duration": float("inf")}, {"subtitles": [{"start": None, "end": 1}]}):
            timeline = {**self.data["timeline"], **change}
            _, value = self.request({"action": "frame", "timeline": timeline, "assets": self.data["assets"], "time": 0})
            self.assertFalse(value["ok"])
        timeline = copy.deepcopy(self.data["timeline"])
        timeline["cues"][0]["imageAssetId"] = "../../secret"
        _, value = self.request({"action": "frame", "timeline": timeline, "assets": self.data["assets"], "time": 0})
        self.assertFalse(value["ok"])

    def test_font_missing_is_explicit(self):
        _, value = self.request({"action": "frame", "timeline": self.data["timeline"], "assets": self.data["assets"], "time": 0, "fontPath": str(self.output / "missing.ttf")})
        self.assertFalse(value["ok"])
        self.assertEqual(value["error"]["code"], "INVALID_ASSET")

    def test_unavailable_glyph_is_not_rendered_as_tofu(self):
        timeline = {**self.data["timeline"], "title": "Missing: \U0010ffff"}
        _, value = self.request({"action": "frame", "timeline": timeline, "assets": self.data["assets"], "time": 0})
        self.assertEqual(value["error"]["code"], "FONT_GLYPHS_MISSING")

    def test_output_cannot_overwrite_input(self):
        output = self.output / "collision"
        output.mkdir(exist_ok=True)
        source = output / "frame.png"
        original = Path(self.data["assets"]["image0"]["path"]).read_bytes()
        source.write_bytes(original)
        request = {"action": "probe", "inputPath": str(source), "outputDir": str(output)}
        path = output / "request.json"
        path.write_text(json.dumps(request), encoding="utf-8")
        completed = subprocess.run([sys.executable, str(ROOT / "python" / "worker.py"), "--request", str(path)], capture_output=True, text=True)
        self.assertEqual(completed.returncode, 1)
        self.assertEqual(source.read_bytes(), original)
        self.assertEqual(json.loads(completed.stdout.splitlines()[-1])["message"], "UNSAFE_PATH")

    def test_duplicate_keys_get_structured_error(self):
        output = self.output / "duplicate"
        output.mkdir(exist_ok=True)
        path = output / "request.json"
        path.write_text('{"action":"health","action":"probe","outputDir":' + json.dumps(str(output)) + '}', encoding="utf-8")
        completed = subprocess.run([sys.executable, str(ROOT / "python" / "worker.py"), "--request", str(path)], capture_output=True, text=True)
        self.assertEqual(completed.returncode, 1)
        self.assertEqual(json.loads((output / "result.json").read_text())["error"]["code"], "INVALID_REQUEST")

    def test_audio_cut_overlay_sum_and_hard_cut_are_authoritative(self):
        timeline = copy.deepcopy(self.data["timeline"])
        timeline["audioSegments"] = [{"sourceStart": .25, "sourceEnd": .75, "start": .5}]
        timeline["audioOverlays"] = [{"assetId": "chime", "start": .5, "gainDb": -6}]
        mapped = assets_mapping(self.data["assets"])
        audio, _ = mix_audio(timeline, mapped, "recording")
        source = decode_audio(mapped["recording"]["path"])
        overlay = decode_audio(mapped["chime"]["path"])
        np.testing.assert_allclose(audio[:, 24000:43200], source[:, 12000:31200] + overlay * (10 ** (-6 / 20)), atol=1e-7)
        self.assertTrue(np.all(audio[:, 48000:] == 0))
        timeline["cues"] = [{"start": .5, "end": 2, "kind": "scene", "imageAssetId": "image0"}, {"start": 2, "end": 5, "kind": "scene", "imageAssetId": "image1"}]
        timeline["subtitles"] = []
        painter = Painter(validate_timeline(timeline, mapped), mapped)
        before = np.asarray(painter.draw(1.99))
        after = np.asarray(painter.draw(2))
        later = np.asarray(painter.draw(2.01))
        self.assertFalse(np.array_equal(before, after))
        np.testing.assert_array_equal(after, later)

    def test_health_reports_actual_readiness_without_paths(self):
        _, value = self.request({"action": "health"})
        self.assertTrue(value["ok"])
        self.assertTrue(value["result"]["ready"])
        self.assertTrue(value["result"]["cjkReady"])
        self.assertFalse(value["result"]["networkEnabled"])
        self.assertNotIn(str(self.output), json.dumps(value))


if __name__ == "__main__":
    unittest.main()
